# Generated by Django 4.1.1 on 2022-12-10 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctionApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_owned', to='auctionApp.item'),
        ),
    ]
