# Generated by Django 4.1.1 on 2022-12-10 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctionApp', '0002_alter_user_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owns', to=settings.AUTH_USER_MODEL),
        ),
    ]
