# Generated by Django 4.1.1 on 2022-12-15 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctionApp', '0004_alter_item_date_posted_alter_item_expiry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('answer', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='questiondetails',
            name='item',
        ),
        migrations.RemoveField(
            model_name='questiondetails',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='questions',
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='assets/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(auto_now=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='assets/'),
        ),
        migrations.DeleteModel(
            name='AnswerDetails',
        ),
        migrations.DeleteModel(
            name='QuestionDetails',
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='questions',
            field=models.ManyToManyField(to='auctionApp.questionanswer'),
        ),
    ]
