# Generated by Django 4.1.2 on 2022-12-13 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctionApp', '0004_alter_item_date_posted_alter_item_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiondetails',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
